#!/usr/bin/env python3
"""
reporting.py - Reporting Module for Red Team Offensive Security Simulator
Author: Brian Dodd
Description: Generates high-fidelity HTML reports from recon and exploit results.
"""

import os
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

# ------------------------------------------
# Professional HTML Template
# ------------------------------------------
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Red Team Report - {target}</title>
<style>
    body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; background-color: #f9f9f9; color: #333; }}
    .container {{ max-width: 1000px; margin: auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
    h1 {{ color: #c0392b; border-bottom: 2px solid #c0392b; padding-bottom: 10px; }}
    h2 {{ color: #2c3e50; margin-top: 30px; }}
    .metadata {{ background: #ecf0f1; padding: 15px; border-left: 5px solid #34495e; margin-bottom: 20px; }}
    table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
    th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
    th {{ background-color: #34495e; color: white; text-transform: uppercase; font-size: 14px; }}
    tr:nth-child(even) {{ background-color: #f2f2f2; }}
    .status-vulnerable {{ color: #e74c3c; font-weight: bold; }}
    .status-success {{ color: #27ae60; font-weight: bold; }}
    .note {{ font-size: 0.9em; color: #666; font-style: italic; }}
</style>
</head>
<body>
<div class="container">
    <h1>Red Team Simulation Report</h1>
    <div class="metadata">
        <p><strong>Target Host:</strong> {target}</p>
        <p><strong>Scan Date:</strong> {date}</p>
        <p><strong>Classification:</strong> PROPRIETARY / CONFIDENTIAL</p>
    </div>

    <h2>Vulnerability & Findings Summary</h2>
    {findings_table}

    <p style="margin-top: 50px; font-size: 12px; color: #999; text-align: center;">
        Generated by Red Team Offensive Simulator v1.0
    </p>
</div>
</body>
</html>
"""

# ------------------------------------------
# Helper: Generate HTML Table
# ------------------------------------------
def generate_findings_table(exploit_results):
    """
    Converts exploit results dictionary to an HTML table.
    """
    if not exploit_results:
        return "<p>No open ports or exploitable findings were detected during this simulation.</p>"

    table_html = "<table>"
    table_html += (
        "<tr>"
        "<th>Port</th><th>Service</th><th>Vector</th><th>Status</th><th>Evidence / Notes</th>"
        "</tr>"
    )

    for port, info in exploit_results.items():
        service = info.get("service", "Unknown")
        findings = info.get("findings", [])

        if not findings:
            table_html += f"<tr><td>{port}</td><td>{service}</td><td colspan='3' style='text-align:center;'>No Vulnerabilities Found</td></tr>"
            continue

        for finding in findings:
            f_type = finding.get("type", "General")
            result = finding.get("result", {})
            status = result.get("status", "DETECTED")
            
            # Apply dynamic styling to status
            status_class = ""
            if "VULNERABLE" in status.upper(): status_class = 'class="status-vulnerable"'
            if "SUCCESS" in status.upper(): status_class = 'class="status-success"'

            # Compile evidence strings
            details_list = []
            
            # Check for credentials
            creds = result.get("credentials")
            if creds:
                details_list.append(f"<b>Account Found:</b> {creds.get('username')} / {creds.get('password')}")

            # Check for specific exploit notes
            notes = result.get("notes") or result.get("type")
            if notes:
                if isinstance(notes, list):
                    details_list.extend(notes)
                else:
                    details_list.append(str(notes))

            details = "<br>".join(details_list) if details_list else "Manual validation required."

            table_html += (
                f"<tr>"
                f"<td>{port}</td>"
                f"<td>{service}</td>"
                f"<td>{f_type}</td>"
                f"<td {status_class}>{status}</td>"
                f"<td class='note'>{details}</td>"
                f"</tr>"
            )

    table_html += "</table>"
    return table_html


# ------------------------------------------
# Main Report Generator
# ------------------------------------------
def generate_report(target, exploit_results, report_dir="./reports"):
    """
    Generates an HTML report for a target and saves it to report_dir.
    """
    try:
        os.makedirs(report_dir, exist_ok=True)

        now_filename = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{target.replace('.', '_')}_report_{now_filename}.html"
        filepath = os.path.join(report_dir, filename)

        findings_table = generate_findings_table(exploit_results)

        html_content = HTML_TEMPLATE.format(
            target=target,
            date=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            findings_table=findings_table
        )

        with open(filepath, "w") as f:
            f.write(html_content)

        logger.info(f"[+] Report successfully generated: {filepath}")
        return filepath

    except Exception as e:
        logger.error(f"[!] Failed to generate report for {target}: {e}", exc_info=True)
        return None
